# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  project: 'Synigo.Integration.Model.csproj'
  majorMinorVersion: 1.1
  # semanticVersion counter is automatically incremented by one in each execution of pipeline
  # second parameter is seed value to reset to every time the referenced majorMinorVersion is changed
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]
  projectName: 'Synigo.OneApi.Model'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install'

- task: NuGetCommand@2
  displayName: 'Restore'
  inputs:
    restoreSolution: '$(solution)'

# Build
- task: DotNetCoreCLI@2
  displayName: 'Build $(projectName)'
  inputs:
    projects: '**/$(projectName).csproj'
    arguments: '--configuration $(BuildConfiguration)'

# Package
- task: DotNetCoreCLI@2
  displayName: 'Pack $(projectName)'
  inputs:
    command: 'pack'
    configuration: $(BuildConfiguration)
    packagesToPack: '**/$(ProjectName)*.csproj'
    packDirectory: '$(build.artifactStagingDirectory)'
    versioningScheme: byBuildNumber # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#yaml-snippet

# Publish
- task: NuGetCommand@2
  displayName: 'Publish $(projectName)'
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactStagingDirectory)/$(ProjectName)*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget Synigo'