# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 1.9.0.$(Rev:r)

variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    project: 'Synigo.Integration.Model.csproj'
    projectName: 'Synigo.OneApi.Model'
    projects:
        - Synigo.OneApi.Model

trigger:
    branches:
        include: 
            - main
pool:
    vmImage: 'windows-latest'

steps:
- ${{ each query in variables.projects }}:

    - task: NuGetToolInstaller@1
      displayName: 'Install'

    - task: NuGetCommand@2
      displayName: 'Restore'
      inputs:
        restoreSolution: '$(solution)'

    # Package
    - task: DotNetCoreCLI@2
      displayName: 'Pack $(projectName)'
      inputs:
        command: 'pack'
        configuration: $(BuildConfiguration)
        packagesToPack: '**/$(projectName).csproj'
        packDirectory: '$(System.DefaultWorkingDirectory)'
        versioningScheme: byBuildNumber # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#yaml-snippet

    # Publish
    - task: NuGetCommand@2
      displayName: 'Publish $(projectName)'
      inputs:
        command: 'push'
        packagesToPush: '$(System.DefaultWorkingDirectory)/**/*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'Nuget Synigo'